
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmartinique # id kubernetes, pour repérer, mise à jour etc.., unique pour chaque namespacexressource
  #1 trio d'unicité : namespace/name/kind
spec:
  replicas: 1
  selector: # système labels selector, marqueurs etc.. pour repérer par la suite et sélectionner
    matchLabels:
      app: appmartinique # comment retrouver mes pods ? (avec quel label ?)
  template: # je mets des labels sur les pods-> le déploiement donenra naissance à des pods auxquels le label nginxlabel1 sera donné
    metadata:
      labels:
        app: appmartinique
    spec:
      volumes:
        - name: volumepartage # verif de la disponibilité de la pvc
          persistentVolumeClaim:
            claimName: mon-espace

      containers:
        - name: nginx
          image: cguillo/sitemartinique
          imagePullPolicy: Always # Je peux delete le pod pour qu'il aille chercher : la nouvelle image sur dockerhub
          volumeMounts:
            - mountPath: /usr/share/nginx/html/img  # c'est l'endroit dans le docker nginx où on veut monter le volume ie où on veut voir les fixchiers qu'on aura plcé grâce à l'init docker
              name: volumepartage
           
      initContainers:
        - name: downloadimages
          image: minio/mc
          imagePullPolicy: Always
          #mc alias set myminio https://myminio.example.net minioadminuser minioadminpassword
          command: ["mc"]
          args: ["cp", "--recursive","s3/cguillo/site_carto/","dossierimage"]
          #env:
           # - name: MC_HOST_s3
            #  value: https://id:pwd@minio.lab.sspcloud.fr# informations récupérable dans storage etc.. mais je veux utiliser les secrets
              #"https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY:$AWS_SESSION_TOKEN@$AWS_S3_ENDPOINT"
                   # https://id:pwd@minio.lab.sspcloud.fr# informations récupérable dans storage etc.. mais je veux utiliser les secrets
          envFrom:
          - configMapRef:
              name: env-configmap
          #- secretRef:
              #name: env-secrets
          
            # https://gist.github.com/troyharvey/4506472732157221e04c6b15e3b3f094
            
          # On copie une image dans le volume en passant par le dossier img créé dans l'init docker pour l'occasion.
          volumeMounts:
            - mountPath: /dossierimage
              name: volumepartage 
