
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: volumepartage
          persistentVolumeClaim:
            claimName: mon-espace

      containers:
        - name: nginx
          image: cguillo/sitemartinique
          volumeMounts:
            - mountPath: /usr/share/nginx/html/img  # c'est l'endroit dans le docker nginx où on veut monter le volume ie où on veut voir les fixchiers qu'on aura plcé grâce à l'init docker
              name: volumepartage
           
      initContainers:
        - name: download_images
          image: curlimages/curl
          args:
            - https://minio.lab.sspcloud.fr/cguillo/site_carto/Anghiera.jpg
            - -o
            - /img/Anghiera.jpg # On copie une image dans le volume en passant par le dossier img créé dans l'init docker pour l'occasion.
          volumeMounts:
            - mountPath: /img
              name: volumepartage
