apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websiteservice
spec:
  rules:
  - host: martiyoupi.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 
              number: 8080
