apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
type: Opaque
data:
  MC_HOST_s3: IUJKTRBMKS4VCC058C3E
  #REDIS_PASSWORD: AAZbUGVXeU5e0ZB

  #echo https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY:$AWS_SESSION_TOKEN@$AWS_S3_ENDPOINT
  #dans la console pour récupérer ce qu'il faut mettre dans MC_HOST_s3
  